#!/usr/bin/env python3
# Generate RAMCloud/scripts/localconfig.py from nodes.txt.
#
# RAMCloud/scripts/config.py does `from localconfig import *`, so we can
# inject the host list and patch common.getHosts() to skip the rcres
# reservation check (we don't run rcres on this CloudLab experiment).
import os
import socket
import sys

if len(sys.argv) != 3:
    print("usage: make_localconfig.py NODES_TXT OUTPUT_PY", file=sys.stderr)
    sys.exit(1)

nodes_path = sys.argv[1]
out_path = sys.argv[2]

with open(nodes_path) as f:
    names = [line.strip() for line in f if line.strip()]

if not names:
    print("ERROR: nodes file is empty: " + nodes_path, file=sys.stderr)
    sys.exit(1)

# Use the short hostname for network connectivity (CloudLab /etc/hosts
# resolves these to the experiment-internal IP).
hosts = []
for idx, name in enumerate(names, start=1):
    try:
        ip = socket.gethostbyname(name)
    except socket.gaierror:
        print("ERROR: cannot resolve %s" % name, file=sys.stderr)
        sys.exit(1)
    hosts.append((name, ip, idx))

# Emit a Python 2-compatible localconfig.py.
body = []
body.append("# Generated by make_localconfig.py - do not edit by hand.")
body.append("# Bypass the rcres reservation check used by common.getHosts().")
body.append("import os")
body.append("os.environ.setdefault('RCRES_DISABLE', '1')")
body.append("")
body.append("hosts = [")
for h, ip, idx in hosts:
    body.append("    (%r, %r, %d)," % (h, ip, idx))
body.append("]")
body.append("")
# Don't override obj_dir - config.py auto-detects 'obj.<branch>' from git.
# Override the default disks (config.py defaults to '-f /dev/sda2,/dev/sdb2'
# which doesn't exist on CloudLab) with a file in /tmp.
body.append("default_disks = '-f /tmp/ramcloud-backup.log'")

with open(out_path, "w") as f:
    f.write("\n".join(body) + "\n")

print("wrote %d hosts to %s" % (len(hosts), out_path))
